# Generated by Django 5.2.6 on 2025-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
