# Generated by Django 5.2.6 on 2025-09-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
