# Generated by Django 5.2.6 on 2025-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
