# Generated by Django 5.2.6 on 2025-09-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
