# Generated by Django 5.2.6 on 2025-09-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
