# Generated by Django 5.2.6 on 2025-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('jersey', 'Jersey'), ('shoes', 'Shoes'), ('equipment', 'Equipment'), ('accessories', 'Accessories'), ('mercnhandise', 'Merchandise'), ('balls', 'Balls'), ('apparel', 'Apparel'), ('bags', 'Bags')], default='general', max_length=255),
        ),
    ]
