# Generated by Django 5.2.6 on 2025-09-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_quantity_remove_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Jersey', 'Jersey'), ('Shoes', 'Shoes'), ('Ball', 'Balls'), ('Accessories', 'Accessories'), ('Bags', 'Bags')], default='Jersey', max_length=50),
        ),
    ]
